name: Upload dotnet package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - run: dotnet build --configuration Release rct
      - name: Create the package
        run: dotnet pack --configuration Release /p:Version=${VERSION} rct
      - name: Publish the package to Nuget
        run: dotnet nuget push rct/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_AUTH_TOKEN}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

